version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build-prod
      - ./mvnw clean -Dmaven.test.skip=true package

artifacts:
  files:
    - appspec.yml
    - scripts/beforeInstall.sh
    - scripts/afterInstall.sh
    - target/wise.war
  discard-paths: yes
