#!/bin/bash
echo "*****************************"
echo "* BEGIN WISE PRECOMMIT HOOK *"
echo "*****************************"
if [ "`git diff --cached --name-status | grep src/main/resources/application-dockerdev.properties | wc -l`" -gt 0 ]; then
  echo "Aborting. You are trying to add application-dockerdev.properties. This file may contain confidential data like passwords."
  echo "If you really want to commit this file, you can commit with -n to bypass this pre-commit hook."
  exit 1
fi
echo "***************************"
echo "* END WISE PRECOMMIT HOOK *"
echo "***************************"
